### ISSUE TITLE
Failure to recreate staffroll.bin

### ISSUE THREAD

**Issue by WhitetailAni** [RoadrunnerWMC/nsmbw-staffroll-tool#1]
When attempting to recreate staffroll.bin after editing it, it returns this and does not create the file::
`Traceback (most recent call last):
  File "J:\nsmbw-staffroll-tool-master\staffroll.py", line 102, in <module>
    main()
  File "J:\nsmbw-staffroll-tool-master\staffroll.py", line 96, in main
    bin = staffroll_lib.saveStaffrollBin(lines)
  File "J:\nsmbw-staffroll-tool-master\staffroll_lib.py", line 435, in saveStaffrollBin
    line.saveToBinFile(f)
  File "J:\nsmbw-staffroll-tool-master\staffroll_lib.py", line 156, in saveToBinFile
    f.write(struct.pack('>II', self.indent, self.num_chars_and_copyrights))
struct.error: argument out of range`

I've double-checked that I'm using the correct command, but still nothing.

**Comment by RoadrunnerWMC** [comment]
Hm, it's probably calculating a negative amount of indentation required to center a very long line, and then failing to save it because it tries to save indentation as an unsigned value. It's definitely a bug, but thinking about exactly how to fix it raises a question... is it really *supposed* an unsigned value, or might the game actually read it as a signed one?

I'll do a bit of in-game testing and report back. Thanks for bringing this up!

As a workaround for now, you can either make sure that every line is at most 31 characters long, or force a specific non-negative indentation for long lines. The syntax for that is to put the indentation value at the start of the line, followed by a colon, e.g. `0:This Line Will Have Zero Indentation Even Though It's Very Long`. But very long lines like that probably won't work well in-game anyway.

**Comment by RoadrunnerWMC** [comment]
The game refuses to display lines with negative indentation (or spawns them several miles off the right edge of the screen?), so the value should definitely be considered unsigned. f4b07ca fixes this by clamping negative-indented lines to 0 indentation and printing a warning. I think this should fix the issue for you -- let me know if it doesn't!

**Comment by WhitetailAni** [comment]
No luck yet.
Though I did add text to the file; could that be it? I'm not sure if your script allows reencryption of the .txt file to have more text lines than the stock staffroll.txt does.
Here's what CMD spits out:
`J:\nsmbw-staffroll-tool-master>py staffroll.py --type txt J:\nsmbw-staffroll-tool-master\staffroll.txt J:\staffroll.bin
Traceback (most recent call last):
  File "J:\nsmbw-staffroll-tool-master\staffroll.py", line 102, in <module>
    main()
  File "J:\nsmbw-staffroll-tool-master\staffroll.py", line 96, in main
    bin = staffroll_lib.saveStaffrollBin(lines)
  File "J:\nsmbw-staffroll-tool-master\staffroll_lib.py", line 438, in saveStaffrollBin
    line.saveToBinFile(f)
  File "J:\nsmbw-staffroll-tool-master\staffroll_lib.py", line 187, in saveToBinFile
    f.write(struct.pack('>I', cval))
struct.error: argument out of range`

Here's my staffroll.txt file, perhaps the script is just broken for me?
[https://drive.google.com/file/d/1V89dvPnFaZYRygU3il2VFI7ou1ZCN9aT/view?usp=sharing](url)

**Comment by RoadrunnerWMC** [comment]
That's actually a similar-looking but separate issue, as it turns out. Should be fixed now (fd6cc21)!

And, yes, you can change the number of lines in the file. The game actually automatically adjusts the text scroll speed depending on how many lines there are, so it always finishes when the music ends.

**Comment by WhitetailAni** [comment]
Yep, works now. Thanks!
